### ISSUE TITLE
Understanding mounce-morphcat

### ISSUE THREAD

**Issue by aaronshaf** [morphgnt/morphological-lexicon#7]
I am trying to better understand the `morphcat` value. What is the difference between `cv` and `v`? Different kind of verbs?

**Comment by jtauber** [comment]
I think Mounce used `cv` to mean compound or complex verb. Basically a verb with a preverb.

For more information on the rest of the tags, see Mounce's analytical lexicon or morphology of biblical greek. To be honest, though, I wouldn't invest too much in them as I only include them as a temporary check.
